### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by 9ary** [devkitPro/devkitppc-rules#7]
I'm trying to package dkppc for nixos, what's the license for this repo?

**Comment by WinterMute** [comment]
Please don't repackage dkppc for nixos. If you really must then provide a pacman package & we'll figure out how best to provide the actual binaries. Drop us a line to support@devkitpro.org & we'll see what we can figure out.

**Comment by 9ary** [comment]
Pacman is not an option. Setting aside how ridiculous it is that you're asking users to install a foreign package manager on their distro, the prebuilt binaries will at a minimum assume that the distro follows the FHS (not the case on NixOS), and has glibc (not the case for distros such as Alpine).

This isn't Windows, there's a reason for distros packaging things rather than letting everyone rely on prebuilt binaries. Please don't be a hostile upstream.

**Comment by WinterMute** [comment]
We're not being hostile. You are.
